### ISSUE TITLE
feat: include header section in the extracted file

### ISSUE THREAD

**Issue by danyill** [axellp/mbg-icd-extractor#2]
I had a play just now with this plugin, thanks for the recent changes.

I notice that having:

  SCL
     Communication

Is not actually schema valid - I think the `Header` element is mandatory. Currently I don't think the Header element is being produced on the ICD files

**Comment by danyill** [comment]
No, I lied, I was caught out by #3.

Not that it might not be quite nice to have a Header section saying what was exported, from where and when 

Can I upcycle this issue to a feature request :stuck_out_tongue_winking_eye:

**Comment by axellp** [comment]
Yeah, no problem! I just implemented this feature in commit a8963e958a1a398847309aa1a0076b1c27387d97. Please let me know how it looks and if other sections need to be added.
