### ISSUE TITLE
feat: Namespaces are not transferred

### ISSUE THREAD

**Issue by danyill** [axellp/mbg-icd-extractor#3]
When the CID file is created we should transfer namespace definitions from the originating document. Currently these are not transferred which will often make an exported CID file schema invalid.

Thank you for your work on this project

**Comment by axellp** [comment]
Hi, @danyill. Thank you for the recent feedback. Could you please explain more or show an example of where these namespace definitions can be found in the originating document?

**Comment by danyill** [comment]
So IEC 61850-6 "prefers" that namespaces are added on the root node.

Here's an example from a typical SCD file we use:

```xml
<SCL xmlns:eIEC61850-6-100="http://www.iec.ch/61850/2019/SCL/6-100" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.iec.ch/61850/2003/SCL" xmlns:esld="https://transpower.co.nz/SCL/SSD/SLD/v0" xmlns:etpc="https://transpower.co.nz/SCL/SCD/Communication/v1" xmlns:IEC_60870_5_104="http://www.iec.ch/61850-80-1/2007/SCL" xmlns:siebase="http://www.siemens.com/energy/2009/09/siprotec5/SieBase" xmlns:siedig="http://www.siemens.com/energy/2011/11/Siedig" xmlns:esel="http://www.selinc.com/2006/61850" xmlns:eGE="http://www.gedigitalenergy.com/multilin" xmlns:ext="http://www.nrec.com" version="2007" revision="B" release="4" xsi:schemaLocation="http://www.iec.ch/61850/2003/SCL SCL.xsd" eIEC61850-6-100:version="2019" eIEC61850-6-100:revision="C" eIEC61850-6-100:release="1">
```

They need to be transferred to the new document. I'd  suggest not checking if they are used by a particular IED, I would just copy them across to the new document.

**Comment by danyill** [comment]
Of possible use: https://github.com/openscd/open-scd/blob/main/packages/plugins/src/menu/ExportCommunication.ts#L72-L73

**Comment by axellp** [comment]
Thanks for letting me know and for the help! 

Commit 8e3ebfd66a5d09ceb22aa80b37514c3d5d79e326 should take care of this. Let me know how it looks!

**Comment by danyill** [comment]
LGTM, thank you for this improvement.
