### ISSUE TITLE
fix: Export fails if communications  are not defined

### ISSUE THREAD

**Issue by danyill** [axellp/mbg-icd-extractor#4]
I get an error when exporting an IED with no ConnectedAP elements and the file does not export.

Here's a sample file:

[sample-ieds.scd.zip](https://github.com/user-attachments/files/18131605/sample-ieds.scd.zip)

**Comment by danyill** [comment]
May I also take this moment to recommend a little Typescript :wink:

**Comment by axellp** [comment]
Hi @danyill, commit 6ad45c2cc932e28a5b4b7a97dd76cf5311cb0dab should fix this issue. Please let me know if you find anything else

**Comment by danyill** [comment]
LGTM, thank you
