### ISSUE TITLE
Datatypes not always correctly generated

### ISSUE THREAD

**Issue by danyill** [axellp/mbg-icd-extractor#5]
In most cases a complete set of datatypes are generated however I have found one IED where that is not true.
I tested two SEL devices and one GE device. The two SEL devices were brought back into the ICT tool without any unexpected errors but the GE device could not be imported.

I know there is one (minor) schema invalidity in the attached SCD file:

[SOM-XAT_2_LDif1_Testing_Before_Comms_Update_Fix_LGOS_Removed_Additional_FixRef_Swapout_112.zip](https://github.com/user-attachments/files/18191495/SOM-XAT_2_LDif1_Testing_Before_Comms_Update_Fix_LGOS_Removed_Additional_FixRef_Swapout_112.zip)

Using this plugin, when I extract a CID file for the GE IED, XAT_BusA_P1 and bring it into the ICT, I get an error message:

[XAT_BusA_P1.zip](https://github.com/user-attachments/files/18191496/XAT_BusA_P1.zip) - the file

![image](https://github.com/user-attachments/assets/cbabea75-dcfd-4490-9a80-c69cf85e649f)

When I examine this, I notice indeed that a data type with id "Vector_1" is missing from the CID file.

Also of note, the other error around Private data CRC not matching may indicate that this plugin is re-writing CDATA sections or perhaps formatting them. GE devices checksum the entire CDATA section and so they must be preserved exactly. I can look into this further at some stage if this is not a helpful comment (and perhaps that should be a separate issue anyways).

**Comment by axelp-mbg** [comment]
Hi @danyill, thanks for letting me know. Commit 3a716e6ae0e47298faead66d534f4d5bf6916f95 should address the issue of missing data types.

As for the CDATA section, the issue appears to come from when the file is formatted. I'll open a separate issue for this case.

**Comment by danyill** [comment]
The fix has worked beautifully, 👏

FYI I tested:

* One Siemens device in Siemens IEC 61850 Configurator
* One SEL device in SEL Architect
* One GE device in GE Enervista
* One NR Electric device in PCS Studio

And all opened without any unexpected errors or problems, so I'd say this plugin is looking really good! 👍  

I'd like to roll it into my own distribution at some stage (except there I would like the extension when extracting to be `iid` and I'm not sure how to approach this).

**Comment by axelp-mbg** [comment]
Right now, it is hard-coded to download a `.cid` file. However, I plan to implement a feature that allows users to choose between receiving a CID, ICD, or IID file. I'll create a new issue for this feature 👍.
