### ISSUE TITLE
fix: Preserve CDATA sections in the IED

### ISSUE THREAD

**Issue by axelp-mbg** [axellp/mbg-icd-extractor#6]
As mentioned in issue #5, the CDATA section found in the IED is not preserved. 

It appears when formatting the output file that this information is removed. GE devices checksum the entire CDATA section, and so they must be preserved precisely.

**Comment by axelp-mbg** [comment]
Fix implemented in commit 84bc25e9b5158c0705049c33ddaf7eb1d4fb01c4

**Comment by danyill** [comment]
The fix has worked beautifully, 👏 Feel free to close this issue now.
