### ISSUE TITLE
feat: Allow users to choose between receiving a CID, ICD, or IID file

### ISSUE THREAD

**Issue by axelp-mbg** [axellp/mbg-icd-extractor#7]
Currently, the IED Extractor is hard-coded to download a CID file of the extracted IED to the user's device.

The plan is to implement a feature that allows users to choose between receiving a CID, ICD, or IID file. The initial idea is to implement it as a Radio element that appears below the list of IEDs where users can select and download one file at a time.

**Comment by axelp-mbg** [comment]
Feature implemented in commit 2c331136c48fc4f06fbceb83e03720df022bfc51

**Comment by danyill** [comment]
Works really nicely and I think the UI is cute :wink: Thanks!
